package com.josenromero.nextletterpuzzle.ui.theme

import androidx.compose.ui.graphics.Color


val light_primary = Color(0xff06b6d4)
val light_onPrimary = Color(0xFFffffff)
val light_primaryContainer = Color(0xFFa9edff)
val light_onPrimaryContainer = Color(0xFF001f26)
val light_secondary = Color(0XFF006875)
val light_onSecondary = Color(0xFFffffff)
val light_secondaryContainer = Color(0xFF9af0ff)
val light_onSecondaryContainer = Color(0xFF001f24)
val light_tertiary = Color(0xFF006493)
val light_onTertiary = Color(0xFFffffff)
val light_tertiaryContainer = Color(0xFFcae6ff)
val light_onTertiaryContainer = Color(0xFF001e30)
val light_background = Color(0xFFfafcff)
val light_onBackground = Color(0xFF001f2a)
val light_surface = Color(0xFFfafcff)
val light_onSurface = Color(0xFF001f2a)
val light_outline = Color(0xFF6f797b)
val light_surfaceVariant = Color(0xFFdbe4e7)
val light_onSurfaceVariant = Color(0xFF3f484b)
val light_scrim = Color(0xFF001f2a)

val dark_primary = Color(0xFF54d7f3)
val dark_onPrimary = Color(0xFF003640)
val dark_primaryContainer = Color(0xFF004e5b)
val dark_onPrimaryContainer = Color(0xFFa9edff)
val dark_secondary = Color(0XFF50d8ec)
val dark_onSecondary = Color(0xFF00363d)
val dark_secondaryContainer = Color(0xFF004f58)
val dark_onSecondaryContainer = Color(0xFF9af0ff)
val dark_tertiary = Color(0xFF8ccdff)
val dark_onTertiary = Color(0xFF00344f)
val dark_tertiaryContainer = Color(0xFF004b70)
val dark_onTertiaryContainer = Color(0xFFcae6ff)
val dark_background = Color(0xFF001f2a)
val dark_onBackground = Color(0xFFbfe9ff)
val dark_surface = Color(0xFF001f2a)
val dark_onSurface = Color(0xFFbfe9ff)
val dark_outline = Color(0xFF899295)
val dark_surfaceVariant = Color(0xFF3f484b)
val dark_onSurfaceVariant = Color(0xFFbfc8cb)
val dark_scrim = Color(0xFF001f2a)